import { Button } from '@mui/material'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useMoralis, useApiContract } from 'react-moralis'
import { useEffect } from 'react'

export default function Home() {
  const {
    authenticate,
    isAuthenticated,
    isAuthenticating,
    user,
    account,
    logout,
    web3,
    enableWeb3,
    deactivateWeb3,
    isWeb3Enabled,
    isWeb3EnableLoading,
    web3EnableError,
  } = useMoralis()

  console.log('account', account)
  console.log('user', user)
  useEffect(() => {
    // if (isAuthenticated) {
    enableWeb3()
    // }
  }, [])
  const onClickConnectWallet = async () => {
    // if (!isAuthenticated) {
    try {
      await authenticate({ signingMessage: 'connect by learn-contract' })
    } catch (ex) {
      console.log(error)
    }
    // }
  }
  const onClickDisconnectWallet = async () => {
    logout()
    debugger
    // web3.eth.currentProvider.disconnect()
    // await window.Moralis.Web3.cleanup()
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Web3 and smart contract test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {isWeb3Enabled && <div>{account}</div>}
        {isWeb3EnableLoading ? (
          <Button variant="contained">Loading...</Button>
        ) : (
          <>
            {isWeb3Enabled ? (
              <Button variant="contained" onClick={onClickDisconnectWallet}>
                Logout
              </Button>
            ) : (
              <Button variant="contained" onClick={onClickConnectWallet}>
                Connect
              </Button>
            )}
          </>
        )}
      </main>
      <footer className={styles.footer}></footer>
    </div>
  )
}
